# Generated by Django 5.2.8 on 2025-11-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_muscle', models.CharField(choices=[('abductors', 'Abductors'), ('abdominals', 'Abdominals'), ('adductors', 'Adductors'), ('biceps', 'Biceps'), ('brachialis', 'Brachialis'), ('calves', 'Calves'), ('chest', 'Chest'), ('forearms', 'Forearms'), ('front_deltoid', 'Front Deltoid'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('lateral_deltoid', 'Lateral Deltoid'), ('lats', 'Lats'), ('lower_back', 'Lower Back'), ('obliques', 'Obliques'), ('quads', 'Quads'), ('rear_deltoid', 'Rear Deltoid'), ('sternocleidomastoid', 'Sternocleidomastoid'), ('traps', 'Traps'), ('triceps', 'Triceps'), ('upper_chest', 'Upper Chest')], max_length=50)),
                ('secondary_muscle', models.CharField(choices=[('abductors', 'Abductors'), ('abdominals', 'Abdominals'), ('adductors', 'Adductors'), ('biceps', 'Biceps'), ('brachialis', 'Brachialis'), ('calves', 'Calves'), ('chest', 'Chest'), ('forearms', 'Forearms'), ('front_deltoid', 'Front Deltoid'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('lateral_deltoid', 'Lateral Deltoid'), ('lats', 'Lats'), ('lower_back', 'Lower Back'), ('obliques', 'Obliques'), ('quads', 'Quads'), ('rear_deltoid', 'Rear Deltoid'), ('sternocleidomastoid', 'Sternocleidomastoid'), ('traps', 'Traps'), ('triceps', 'Triceps'), ('upper_chest', 'Upper Chest')], max_length=50)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Body Weight'), ('freeweight', 'Free Weight'), ('machine', 'Machine')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
